# Generated by Django 4.2.1 on 2023-05-30 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('firstname', models.CharField(max_length=20, verbose_name='Имя')),
                ('middlename', models.CharField(max_length=20, verbose_name='Отчество')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('email', models.EmailField(max_length=254, verbose_name='Эл. почта')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='Корпоративный телефон')),
                ('extension', models.IntegerField(blank=True, null=True, verbose_name='Короткий номер')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('change_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_fired', models.BooleanField(blank=True, default=False, verbose_name='Уволен')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='employees', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['lastname'],
            },
        ),
    ]
