# Generated by Django 4.2.1 on 2023-05-30 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '__first__'),
        ('employees', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_method', models.CharField(choices=[('LP', 'Логин/пароль'), ('ES', 'ЭЦП')], default='LP', max_length=2, verbose_name='Способ входа')),
                ('role', models.CharField(choices=[('US', 'Пользователь'), ('AD', 'Администратор')], default='US', max_length=2, verbose_name='Роль в системе')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('change_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resources.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee')),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
                'ordering': ['pub_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='account'),
        ),
    ]
