# Generated by Django 4.2.1 on 2023-06-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('PN', 'Персональный'), ('GN', 'Общий')], default='PN', max_length=2, verbose_name='Тип аккаунта'),
        ),
    ]
